# Generated by Django 3.1.2 on 2020-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='BRDDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Brand Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='BRDName',
            field=models.CharField(max_length=40, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARDesc',
            field=models.TextField(blank=True, null=True, verbose_name='Variant Description'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='VARName',
            field=models.CharField(max_length=40, verbose_name='Variant Name'),
        ),
    ]
