# Generated by Django 3.1.2 on 2021-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210102_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDAvaliable',
            field=models.BooleanField(default=True, verbose_name='Avaliable'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
